apiVersion: v1
kind: ConfigMap
metadata:
  name: checkoutservice
data:
  PRODUCT_CATALOG_SERVICE_ADDR: "productcatalogservice:3550"
  SHIPPING_SERVICE_ADDR: "shippingservice:50051"
  PAYMENT_SERVICE_ADDR: "paymentservice:50051"
  EMAIL_SERVICE_ADDR: "emailservice:8080"
  CURRENCY_SERVICE_ADDR: "currencyservice:7000"
  CART_SERVICE_ADDR: "cartservice:7070"
  PORT: "5050"
  DISABLE_PROFILER: "1"