apiVersion: v1
kind: Service
metadata:
  name: checkoutservice
spec:
  type: ClusterIP # by default ClusterIP
  selector:
    app: checkoutservice
    project: hipstershop
    tier: app
  ports:
  - protocol: TCP
    port: 5050 #service-port
    targetPort: 5050 #container-port