apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cartservice
  namespace: argocd
spec:
  project: default
  source:
    #repoURL: https://github.com/vajrapu-srikanth02/kubernetes-argocd.git
    repoURL: https://gitlab.com/demo6955435/kubernetes-argocd.git
    targetRevision: main
    path: cartservice
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true 
      selfHeal: true