apiVersion: v1
kind: Service
metadata:
  name: paymentservice
spec:
  type: ClusterIP # by default ClusterIP
  selector:
    app: paymentservice
    project: hipstershop
    tier: app
  ports:
  - protocol: TCP
    port: 50051 #service-port
    targetPort: 50051 #container-port