apiVersion: v1
kind: Service
metadata:
  name: productcatalogservice
spec:
  type: ClusterIP # by default ClusterIP
  selector:
    app: productcatalogservice
    project: hipstershop
    tier: app
  ports:
  - protocol: TCP
    port: 3550 #service-port
    targetPort: 3550 #container-port