apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  clusterIP: None # by default ClusterIP type: ClusterIP
  selector:
    app: redis
    project: hipstershop
    tier: db
  ports:
  - protocol: TCP
    port: 6379 #service-port
    targetPort: 6379 #container-port