apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  labels:
    app: redis
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: redis
      project: hipstershop
      tier: db
  serviceName: "redis"
  template:
    metadata:
      labels:
        app: redis
        project: hipstershop
        tier: db
    spec:
      containers:
        - name: redis
          image: redis
          ports:
          - containerPort: 6379
          resources:
            requests:
              cpu: 70m
              memory: 200Mi              
            limits:
              cpu: 125m
              memory: 256Mi
          volumeMounts:
          - name: redis-data
            mountPath: /data
  volumeClaimTemplates:
  - metadata: 
      name: redis-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "ebs-sc" #  "default"
      resources:
        requests:
          storage: 1Gi
