apiVersion: v1
kind: Service
metadata:
  name: currencyservice
spec:
  type: ClusterIP # by default ClusterIP
  selector:
    app: currencyservice
    project: hipstershop
    tier: app
  ports:
  - protocol: TCP
    port: 7000 #service-port
    targetPort: 7000 #container-port