apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: LoadBalancer
  selector:
    app: frontend
    project: hipstershop
    tier: web
  ports:
  - protocol: TCP
    port: 80 #service-port
    targetPort: 8080 #container-port
