apiVersion: v1
kind: Service
metadata:
  name: emailservice
spec:
  type: ClusterIP # by default ClusterIP
  selector:
    app: emailservice
    project: hipstershop
    tier: app
  ports:
  - protocol: TCP
    port: 8080 #service-port
    targetPort: 8080 #container-port