apiVersion: v1
kind: Service
metadata:
  name: recommendationservice
spec:
  type: ClusterIP # by default ClusterIP
  selector:
    app: recommendationservice
    project: hipstershop
    tier: app
  ports:
  - protocol: TCP
    port: 8080 #service-port
    targetPort: 8080 #container-port